config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "tweets#index"
  namespace :tweets do
    resources :searches, only: :index
    
  end

  
  

  resources :tweets do
    resources :comments, only: [:create]
    # collection do  
    #   get 'search'  
    # end 
  end  
  resources :comments, only: [:destroy]
  resources :users, only: :show
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  
  belongs_to :user  
  validates :text, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  # validates :text, presence: true, unless: :image?
  validates :text,:image, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy  #「dependent: :destroy」は、この場合「投稿が削除された時に、同時にコメントも消去する」という意味です
  mount_uploader :image, ImageUploader

  # google_map使用時の記載
  # geocoded_by :address
  # after_validation :geocode

  # def self.search(search)
  #   return Tweet.all unless search
  #   Tweet.where('text LIKE(?)', "%#{search}%")
  # end
  # 同じ意味下記、検索機能

  def self.search(search)
    if search
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end


  # private
  # def geocode
  #   uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=#{Rails.application.secrets.google_map_api}")
  #   res = HTTP.get(uri).to_s
  #   response = JSON.parse(res)
  #   self.latitude = response["results"][0]["geometry"]["location"]["lat"]
  #   self.longitude = response["results"][0]["geometry"]["location"]["lng"]
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments


  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # comment = Comment.create(comment_params)
    # redirect_to "/tweets/#{comment.tweet.id}"
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id])  }
      format.json
    end  
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    # redirect_to tweets_path
    redirect_to "/tweets/#{comment.tweet_id}" #超つまづいた
    
  end


  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end

end

app/controllers/tweets/searches_controller.rb
class Tweets::SearchesController < ApplicationController

  def index
    @tweets = Tweet.search(params[:keyword])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(6)
    @random = Tweet.order("RAND()").limit(1)

  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    
  end  

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show 
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user) 
  end

  

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
    # params.require(:tweet).permit(:image, :text,:address, :latitude, :longitude).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(3).order("created_at DESC")
  end

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.container
  - if current_user
    -# - @comment = Comment.new unless @comment
    = form_for [@tweet,@comment] , id: "new_comment" do |f|
      = f.text_field :text, class: 'form__message', placeholder: 'コメント'
      .form__mask
      = f.submit 'Send', class: 'form__submit'

  - else
    %strong
      %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

  .comments
    %h4 ＜コメント一覧＞
    - if @comments
      - @comments.each do |comment|
        %p
          %strong
            = link_to comment.user.nickname, "/users/#{comment.user_id}"
            ：
          = comment.text
          - if user_signed_in? && current_user.id == comment.user_id
            = link_to "削除","/comments/#{comment.id}", method: :delete, class: "comment-delete"
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1.0,minimum-scale=1.0", :name => "viewport"}/
    %title ShootingSpotShare
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    -# %script(src="//maps.google.com/maps/api/js?v=3.23")
    -# %script(src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js")
    -# %script(src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript")
    -# %script(src="/javascripts/gmaps_google.js")
  %body

    = yield

app/views/tweets/_header-bottom.html.haml
.header-bottom
 
  .login-menu
  - if user_signed_in?
    .login-menu-btn-left 
      = link_to "#{current_user.nickname}", "/users/#{current_user.id}",class: "post"
      = link_to "ログアウト",destroy_user_session_path, method: :delete,class: "post"
      = link_to "投稿する", '/tweets/new', class: "post"
      
  - else     
    .login-menu-btn-left
      = link_to "ログイン",new_user_session_path, class: "post"
    .login-menu-btn-right 
      = link_to "新規登録",new_user_registration_path, class: 'post'

app/views/tweets/_header-top.html.haml
.header-top
  %h1.title
    = link_to "ShootingSpotShare", "/tweets" ,class:"main-title"
    %span.title-sub 撮影スポット共有しよう。
    

app/views/tweets/_search.html.haml
.menu
  = form_tag(tweets_searches_path,method: 'get') do
    = text_field_tag :keyword, "",placeholder: "  キーワード  [例: 桜]", class: "search-box"
    = submit_tag 'Search', name: nil, class: "search-submit"

app/views/tweets/create.html.haml
.contents
  .success
    %h3
      投稿が完了やで下記絶対に押してや
    %h4
      (※タイトルも写真も両方投稿せんと表示されへんで)
    = link_to "絶対に押してね", "/tweets" ,class:"create-btn"

app/views/tweets/destroy.html.haml
.contents
  .success
    %h3
      削除完了やで！
    = link_to "絶対に押してね", "/tweets" ,class:"create-btn"

app/views/tweets/edit.html.haml
.wrapper
  .header
    = render partial: 'header-top'
    = render partial: 'header-bottom'

  .form
    = form_for @tweet do |f|
      = f.text_field :text, class: 'form__message', placeholder: 'タイトル'
      -# = f.text_field :name, class: 'form__name', placeholder: 'ニックネーム'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          -# = fa_icon 'image', class: 'icon'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form__submit'
      

app/views/tweets/index.html.haml
.wrapper
  .header
    = render partial: 'header-top'
    = render partial: 'header-bottom'
  .top-page
    = render partial: 'search'
    -@random.each do |tweet|
      .main-photo{style: "background-image: url(#{tweet.image});"}
        

  .top-photos
    %h2 PHOTOS
    %ul.top-photos-nav
      %li.trend
        -# トレンド
      %li.select
        -# セレクト
      %li.new
        -# 新着

  .photos-holder
    %ul.photo-holder
      - @tweets.each do |tweet|
        %li.images
          .images-holder{style: "background-image: url(#{tweet.image});"}
          -# = tweet.image
          %p.image-title
            = tweet.text
          %p.image-name
            %a{href: "/users/#{tweet.user.id}"}
              投稿者:
              = tweet.user.nickname
            -# = tweet.name
          = link_to "詳細","/tweets/#{tweet.id}", method: :get, class: "image-delete"
          - if user_signed_in? && current_user.id == tweet.user_id
            = link_to "削除","/tweets/#{tweet.id}", method: :delete, class: "image-delete"
            = link_to "編集","/tweets/#{tweet.id}/edit", method: :get, class: "image-delete"
  = paginate(@tweets)
      

app/views/tweets/new.html.haml
.wrapper
  .header
    = render partial: 'header-top'
    = render partial: 'header-bottom'
  .form
    = form_for @tweet do |f|
      = f.text_field :text, class: 'form__message', placeholder: 'タイトル'
      -# = f.text_field :address, class: 'form__message', placeholder: '撮影場所住所(任意)'
      -# = f.text_field :name, class: 'form__name', placeholder: 'ニックネーム'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          -# = fa_icon 'image', class: 'icon'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form__submit'

app/views/tweets/searches/index.html.haml
.wrapper
  .header
    = render partial: 'tweets/header-top'
    = render partial: 'tweets/header-bottom'
  .top-page
    = render partial: 'tweets/search'
    - @tweets.each do |tweet|
      .main-photo{style: "background-image: url(#{tweet.image});"}    

app/views/tweets/show.html.haml
.wrapper
  .header
    = render partial: 'header-top'
    = render partial: 'header-bottom'
  .top-page
    %p.main-user-name
      %a{href: "/users/#{@tweet.user.id}"}
        = @tweet.user.nickname
        さんの投稿やで
    .main-photo{style: "background-image: url(#{@tweet.image});"}
    - if user_signed_in? && current_user.id == @tweet.user_id 
      = link_to "削除","/tweets/#{@tweet.id}", method: :delete, class: "image-delete"
      = link_to "編集","/tweets/#{@tweet.id}/edit", method: :get, class: "image-delete"
    -# #map
    -#   :javascript
    -#     function initMap() {

    -#       var test = {lat: #{@tweet.latitude}, lng: #{@tweet.longitude}};
    -#       var map = new google.maps.Map(document.getElementById('map'), {
    -#         zoom: 15,
    -#         center: test
    -#       });
    -#       var transitLayer = new google.maps.TransitLayer();
    -#       transitLayer.setMap(map);

    -#       var contentString = '住所：#{@tweet.address}';
    -#       var infowindow = new google.maps.InfoWindow({
    -#         content: contentString
    -#       });

    -#       var marker = new google.maps.Marker({
    -#         position:test,
    -#         map: map,
    -#         title: contentString
    -#       });

    -#       marker.addListener('click', function() {
    -#         infowindow.open(map, marker);
    -#       });
    -#     }
    -#   %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?v=3.exp&key=#{Rails.application.secrets.google_map_api}&callback=initMap"}
    .container-main
      = render partial: 'comments/comment'
      -# - if current_user
      -#   -# - @comment = Comment.new unless @comment
      -#   = form_for [@tweet,@comment] , id: "new_comment" do |f|
      -#     = f.text_field :text, class: 'form__message', placeholder: 'コメント'
      -#     .form__mask
      -#     = f.submit 'Send', class: 'form__submit'

      -# - else
      -#   %strong
      -#     %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

      -# .comments
      -#   %h4 ＜コメント一覧＞
      -#   - if @comments
      -#     - @comments.each do |comment|
      -#       %p
      -#         %strong
      -#           = link_to comment.user.nickname, "/users/#{comment.user_id}"
      -#           ：
      -#         = comment.text
      -#       - if user_signed_in? && current_user.id == comment.user_id
      -#         = link_to "削除","/tweets/#{comment.id}", method: :delete, class: "image-delete"
              

app/views/tweets/update.html.haml
.contents
  .success
    %h3
      編集完了やで！もう一回言うで編集完了やで！！
    = link_to "絶対に押してね", "/tweets" ,class:"create-btn"

app/views/users/show.html.haml
.wrapper
  .header
    = render partial: 'tweets/header-top'
    = render partial: 'tweets/header-bottom'
  .top-page
    %p.main-user-name
      = @nickname
      さんの投稿一覧
    - @tweets.each do |tweet|
      .main-photo{style: "background-image: url(#{tweet.image});"}
      - if user_signed_in? && current_user.id == tweet.user_id
        = link_to "削除","/tweets/#{tweet.id}", method: :delete, class: "image-delete"
        = link_to "編集","/tweets/#{tweet.id}/edit", method: :get, class: "image-delete"
          
  = paginate(@tweets)      
    